# Generated by Django 5.0.3 on 2024-03-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_attendance', '0002_alter_attendancerecord_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'verbose_name_plural': 'Add Attendance'},
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='clock_in',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='clock_out',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='employee',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='shift',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
