# Generated by Django 5.0.3 on 2024-03-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_attendance', '0003_alter_attendancerecord_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='clock_in',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='clock_out',
            field=models.IntegerField(null=True),
        ),
    ]
