# Generated by Django 5.0.3 on 2024-04-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_attendance', '0004_alter_attendancerecord_clock_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='hours',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
