# Generated by Django 5.0.3 on 2024-04-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_attendance', '0005_attendancerecord_date_attendancerecord_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='clock_in',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='clock_out',
            field=models.DateTimeField(null=True),
        ),
    ]
