# Generated by Django 5.0.3 on 2024-04-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_attendance', '0006_alter_attendancerecord_clock_in_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'verbose_name_plural': 'Add Attendence'},
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='absent',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='late',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
