# Generated by Django 5.0.3 on 2024-04-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_attendance', '0007_alter_leaverequest_options_attendancerecord_absent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='basic_salary',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='gorss_salary',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='total_daily_allowance',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='absent',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='clock_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='clock_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='late',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='shift',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
