# Generated by Django 5.0.3 on 2024-04-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_attendance', '0008_attendancerecord_basic_salary_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'verbose_name_plural': 'Leave Request'},
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='allowed_working_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
