# Generated by Django 5.0.3 on 2024-04-03 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_attendance', '0009_alter_leaverequest_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'verbose_name_plural': 'Leave Requests'},
        ),
        migrations.RenameField(
            model_name='attendancerecord',
            old_name='employee',
            new_name='employee_name',
        ),
    ]
