# Generated by Django 5.0.3 on 2024-03-27 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0003_alter_employee_dept_alter_employee_role'),
        ('reporting_officers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='allowance',
            field=models.IntegerField(default=0, null=True, verbose_name='Total Daily Allowance'),
        ),
        migrations.AddField(
            model_name='employee',
            name='officers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting_officers.data', verbose_name='Reporting Officer'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bonus',
            field=models.IntegerField(default=0, verbose_name='Basic Salary'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(default=0, verbose_name='Salary Cap'),
        ),
    ]
