# Generated by Django 5.0.3 on 2024-04-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0004_employee_allowance_employee_officers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Title',
            field=models.CharField(choices=[('Syed', 'Syed'), ('Mirza', 'Mirza'), ('Non-Syed', 'Non Syed')], default='Non-Syed', max_length=10),
        ),
    ]
