# Generated by Django 5.0.3 on 2024-04-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0005_employee_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='allowed_working_hours',
            field=models.CharField(choices=[('Flexible', 'Flexible'), ('4', '4'), ('8', '8')], max_length=8, null=True),
        ),
    ]
