# Generated by Django 5.0.3 on 2024-03-18 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_information',
            name='registration_number',
        ),
    ]
