# Generated by Django 5.0.3 on 2024-03-18 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_remove_personal_information_registration_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Educational_Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
                ('institue', models.CharField(max_length=100)),
                ('grade', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=2)),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.personal_information')),
            ],
        ),
    ]
