# Generated by Django 5.0.3 on 2024-03-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_educational_background'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educational_background',
            options={'verbose_name': 'Educational Background', 'verbose_name_plural': 'Educational Background'},
        ),
        migrations.AlterModelOptions(
            name='personal_information',
            options={'verbose_name': 'Personal Information', 'verbose_name_plural': 'Personal Informations'},
        ),
        migrations.AddField(
            model_name='educational_background',
            name='passing_year',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='educational_background',
            name='degree',
            field=models.CharField(max_length=100, verbose_name='Title of Degree/Certificate/Sanad'),
        ),
        migrations.AlterField(
            model_name='educational_background',
            name='institue',
            field=models.CharField(max_length=100, verbose_name='Institute/Hoza/Madrasa'),
        ),
    ]
