# Generated by Django 5.0.3 on 2024-03-18 20:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0004_alter_educational_background_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.CharField(max_length=100, verbose_name='Copy of National ID card')),
                ('photo', models.CharField(max_length=100, verbose_name='2 Passport Size Photographs')),
                ('documents', models.CharField(max_length=100, verbose_name='Copy of all educational documents')),
                ('teaching', models.CharField(max_length=100, verbose_name='Teaching Experience letter (if applicable)')),
                ('skills', models.CharField(max_length=100, verbose_name='Skill certificates (if any)')),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.personal_information')),
            ],
        ),
        migrations.CreateModel(
            name='otherProfessionalSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100, verbose_name='Organization/company/Employer Name')),
                ('_from', models.CharField(max_length=100, verbose_name='From')),
                ('to', models.CharField(max_length=100, verbose_name='To')),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.personal_information')),
            ],
            options={
                'verbose_name': 'Other Professional Skill',
                'verbose_name_plural': 'Other Professional Skills',
            },
        ),
        migrations.CreateModel(
            name='professionalSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000, verbose_name='Description')),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.personal_information')),
            ],
            options={
                'verbose_name': 'PROFESSIONAL SKILL',
                'verbose_name_plural': 'PROFESSIONAL SKILLS',
            },
        ),
        migrations.CreateModel(
            name='refrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relation', models.CharField(max_length=100, verbose_name='Relation with applicant')),
                ('contact_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 12 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.personal_information')),
            ],
            options={
                'verbose_name': 'Reference',
                'verbose_name_plural': 'References',
            },
        ),
        migrations.CreateModel(
            name='relgiousOrPolicts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100, verbose_name='Name of party or association')),
                ('_from', models.CharField(max_length=100, verbose_name='From')),
                ('to', models.CharField(max_length=100, verbose_name='To')),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.personal_information')),
            ],
            options={
                'verbose_name': 'RELIGIOUS OR Political Affiliation',
                'verbose_name_plural': 'RELIGIOUS OR Political Affiliations',
            },
        ),
    ]
