# Generated by Django 5.0.3 on 2024-03-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0005_documents_otherprofessionalskill_professionalskills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_information',
            name='registration_num',
            field=models.CharField(editable=False, max_length=10, null=True, unique=True, verbose_name='It will be automoatical generate'),
        ),
    ]
