# Generated by Django 5.0.3 on 2024-03-27 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0007_alter_personal_information_registration_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='id_card',
        ),
        migrations.AddField(
            model_name='documents',
            name='documen',
            field=models.ImageField(null=True, upload_to='', verbose_name='Only Education Documents(If you need then use this otherwise skip this)'),
        ),
        migrations.AddField(
            model_name='documents',
            name='document',
            field=models.ImageField(null=True, upload_to='', verbose_name='Only Education Documents(If you need then use this otherwise skip this)'),
        ),
        migrations.AddField(
            model_name='educational_background',
            name='degree_image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Image of Any Degree/Certificate/Sanad'),
        ),
        migrations.AddField(
            model_name='otherprofessionalskill',
            name='certificte',
            field=models.ImageField(null=True, upload_to='', verbose_name='Related Image'),
        ),
        migrations.AddField(
            model_name='personal_information',
            name='cnic_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='relgiousorpolicts',
            name='assosiation',
            field=models.ImageField(null=True, upload_to='', verbose_name='Related Image'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='documents',
            field=models.ImageField(upload_to='', verbose_name='Copy of all educational documents'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name='Passport Size Photographs'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='skills',
            field=models.ImageField(upload_to='', verbose_name='Skill certificates (if any)'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='teaching',
            field=models.ImageField(null=True, upload_to='', verbose_name='Teaching Experience letter (if applicable)'),
        ),
        migrations.CreateModel(
            name='Resignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resignation_date', models.DateField(verbose_name='Resignation Date')),
                ('reason', models.TextField(verbose_name='Reason for Resignation')),
                ('personal_inf', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my', to='details.personal_information')),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.personal_information')),
            ],
            options={
                'verbose_name': 'Resignation',
                'verbose_name_plural': 'Resignations',
            },
        ),
    ]
