# Generated by Django 5.0.3 on 2024-03-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0008_remove_documents_id_card_documents_documen_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resignation',
            options={'verbose_name': 'Only Use When you want to resign from office', 'verbose_name_plural': 'Only Use When you want to resign from office'},
        ),
        migrations.AddField(
            model_name='resignation',
            name='Approval',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='resignation',
            name='experience_letter',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='resignation',
            name='resignation_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
