# Generated by Django 5.0.3 on 2024-04-01 23:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0009_alter_resignation_options_resignation_approval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_information',
            name='cnic',
            field=models.CharField(help_text='format: xxxxx-xxxxxxx-x', max_length=15, validators=[django.core.validators.RegexValidator(message="CNIC must be in the format: '00000-0000000-0'", regex='^\\d{5}-\\d{7}-\\d{1}$')]),
        ),
    ]
