# Generated by Django 5.0.3 on 2024-04-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0010_alter_personal_information_cnic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_information',
            name='alternate_contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='personal_information',
            name='contact_number',
            field=models.CharField(max_length=15),
        ),
    ]
